
[fusion_crafter]
	#How much FE the Fusion Package Crafter should hold.
	#Range: > 0
	energy_capacity = 5000
	#How much FE/t the Fusion Package Crafter should use.
	#Range: > 0
	energy_usage = 5
	#Should the Fusion Package Crafter draw energy from ME systems.
	draw_me_energy = true

